title: "Fernando Sousa Silva"
description: "Plano de Desenvolvimento Individual (PDI)"
baseurl: "/PDI" # Necessário pois o projeto está no repositório /PDI e não na raiz do seu GitHub
url: "https://nandohss.github.io"
theme: minima
