title: "Meu Site"
description: "Plano de Desenvolvimento Individual (PDI)"
baseurl: "" # Deixe vazio se você estiver publicando na raiz do domínio do usuário
url: "https://nandohss.github.io"
theme: minima
